services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MCP_GATEWAY_DOMAIN=${MCP_GATEWAY_DOMAIN}
      - MCP_GATEWAY_PORT=3121
    extra_hosts:
      - "localhost:127.0.0.1"
    network_mode: "host"
    restart: unless-stopped
  web_search:
    build:
      context: ./servers/web_search
      dockerfile: Dockerfile
    environment:
      - TAVILY_SEARCH_API_KEY=${TAVILY_SEARCH_API_KEY}
      - MCP_SERVER_PORT=9712
    network_mode: "host"
    restart: unless-stopped
