services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    extra_hosts:
      - "localhost:127.0.0.1"
    network_mode: "host"
  web_search:
    build:
      context: ./servers/web_search
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - TAVILY_SEARCH_API_KEY=${TAVILY_SEARCH_API_KEY}
    network_mode: "host"
